# ansible-playbook --ask-vault-pass -i inventory.ini -K playbooks/check_top_ips.yml
---
- name: CHECK TOP CONNECTING IPS AND REPORT ERRORS
  hosts: all
  gather_facts: false
  become: "{{ enable_become | default(false) }}"
  serial: 4
  vars_files:
    - ../.secrets/secret_vars.yml

  tasks:
    - name: GET TOP CONNECTING IPS & THEIR CONNECTION COUNTS
      shell: 'netstat -tn | awk "{print $5}" | grep -E -o "([0-9]{1,3}[\\.]){3}[0-9]{1,3}" | sort | uniq -c | sort -nr'
      register: top_ips_output
      changed_when: false

    - name: DISPLAY TOP CONNECTING IPS
      debug:
        msg: "{{ top_ips_output.stdout_lines }}"


