# ansible-playbook --ask-vault-pass -i inventory.ini -K playbooks/vm_services/mintdns_service.yml
- name: MINTDNS RESTART SERVICES
  hosts: MintDNS
  gather_facts: false
  become: true
  serial: 1
  vars_files:
    - ../../../.secrets/secret_vars.yml

  tasks:
    - name: RESTART SPECIFIED SERVICES
      command: systemctl restart "{{ item }}"
      loop:
        - accounts-daemon.service
        - acpid.service
        - avahi-daemon.service
        - colord.service
        - containerd.service
        - cron.service
        - cups-browsed.service
        - cups.service
        - dbus.service
        - docker.service
        - haveged.service
        - irqbalance.service
        - kerneloops.service
        - ModemManager.service
        - networkd-dispatcher.service
        - NetworkManager.service
        - nmbd.service
        - packagekit.service
        - polkit.service
        - rsyslog.service
        - rtkit-daemon.service
        - sddm.service
        - smbd.service
        - snapd.service
        - ssh.service
        - systemd-journald.service
        - systemd-logind.service
        - systemd-resolved.service
        - systemd-timesyncd.service
        - systemd-udevd.service
        - udisks2.service
        - unattended-upgrades.service
        - upower.service
        - user@1000.service
        - wpa_supplicant.service
      register: restart_result
      ignore_errors: true

    - name: OUTPUT RESTART RESULTS
      debug:
        msg: "Service {{ item.item }} restart result: {{ item.rc }} - {{ item.stdout }}{{ item.stderr }}"
      loop: "{{ restart_result.results }}"
      when: item.rc is defined

