#ansible-playbook --ask-vault-pass -i inventory.ini -K playbooks/docker_stats.yml
---
- name: CHECK DOCKER STATS FOR ALL CONTAINERS
  hosts: all
  gather_facts: true  # This is the default; you can set it to false to disable fact gathering
  become: "{{ enable_become | default(false) }}"
  serial: 1
  vars_files:
    - ../.secrets/secret_vars.yml

  tasks:
    - name: CHECK DOCKER DAEMON IS RUNNING
      command: docker info
      register: docker_info
      changed_when: false
      failed_when: false

    - name: ABORT IF DOCKER IS NOT AVAILABLE
      fail:
        msg: "Docker daemon is not running or not accessible on this host."
      when: docker_info.rc != 0

    - name: GET DOCKER CONTAINER STATS
      shell: docker ps --format '{{ "{{ json ." }} }}'
      register: docker_container_output
      changed_when: false

    - name: CONVERT DOCKER CONTAINER STATS TO LIST
      set_fact:
        container_stats: "{{ docker_container_output.stdout_lines | map('from_json') | list }}"
      when: docker_container_output.stdout != ""

    - name: NO CONTAINERS RUNNING
      debug:
        msg: "No Docker containers are currently running."
      when: docker_container_output.stdout == ""

    - name: DISPLAY SPECIFIC DOCKER STATS FOR EACH CONTAINER
      debug:
        msg:
          - "Name: {{ item.Names | default('N/A') }}"
          - "CreatedAt: {{ item.CreatedAt | default('N/A') }}"
          - "Image: {{ item.Image | default('N/A') }}"
          - "ID: {{ item.ID | default('N/A') }}"
          - "Size: {{ item.Size | default('N/A') }}"
          - "Ports: {{ item.Ports | default('N/A') }}"
          - "Network: {{ item.Networks | default('N/A') }}"
          - "RunningFor: {{ item.RunningFor | default('N/A') }}"
          - "State: {{ item.State | default('N/A') }}"
          - "Status: {{ item.Status | default('N/A') }}"
      loop: "{{ container_stats | default([]) }}"
      loop_control:
        label: ""
